### ISSUE TITLE
Allow to specify the hours per day on the command line

### ISSUE THREAD

**Issue by elboletaire** [kriskbx/gitlab-time-tracker#21]
We use gtt to extract information about our workers' time spent, and every worker has a different time per day schedule.

I've seen that I can specify `oursPerDay` in the yaml file, but not via command line (I've already checked [`gtt-report.js`][gtt-report]).

An `--hours_per_day` param would be much appreciated. 

I've also noticed that setting `timeFormat` defines the time format for all the times shown, if we could show the overall time spent in hours only in the `TIME STATS` part would work as a workaround for us instead of having to specify `--hours_per_day`. I guess there's no way to do that currently, right?

Thanks in advance :)

[gtt-report]: https://github.com/kriskbx/gitlab-time-tracker/blob/master/src/gtt-report.js#L27

**Comment by kriskbx** [comment]
Sure, I can add an `--hours_per_day`option. I haven't done that because working hours per day for what I know are usually 8 - maybe 6 in some Scandinavian countries. This is something you define once and usually never change it.

I would love to implement a way of specifying the time format for different parts of the report. Let's discuss this first: adding multiple options like `statsTimeFormat`, `issueTimeFormat`, ... is kinda bugging me. I did that with the columns: `issueColumns`, `mergeRequestColumns` and I don't like it. I would do something like this in the config:
```yaml
timeFormat:
    stats: "[hours_overall]h"
    issues: ...
```
If you use a string instead of an array in your config, it uses the given format everywhere. Additionally I would implement some bulky command line options: `--time_format_stats`, `--time_format_issues`, ... If you use only `--time_format` it uses the given format everywhere again.

I would also love to refactor the whole columns thing to work the same way. What do you think about it? Do you have any better or more "clean & easy" way of configuring this?

**Comment by elboletaire** [comment]
Yeah working with arrays with various levels makes sense if you're working with yaml 😃

**Comment by kriskbx** [comment]
I just released version `1.6.9` including the `--hours_per_day` option. Still working on the config though.

**Comment by elboletaire** [comment]
Perfect @kriskbx! Really much appreciated 😃

**Comment by elboletaire** [comment]
Should I close the issue? Or will you track in this same issue the `timeFormat` stuff?

**Comment by kriskbx** [comment]
Keep it open. :)

**Comment by kriskbx** [comment]
I just pushed the first draft of the new time format configuration to the master branch (didn't releaed it yet, though). Can you do me favor by checking it out and giving me your feedback?

Do you need those command line options `--time_format_stats`, `--time_format_issues`, etc.? I'm thinking about dropping those as well as `--issue_columns`, `--merge_request_columns` and make the whole time format and column-thing configuration only. I want to keep the command line API as simple as possible, but highly configurable via the yaml files. What do you think about this?

**Comment by elboletaire** [comment]
Of course @kriskbx, when I arrive home today (I'm at work now) I'll try to.

Just to clarify, finally the format is the stated above?

~~~yaml
timeFormat:
    stats: "[hours_overall]h"
    issues: ...
~~~

I won't use the inline arguments for the formats, so don't do it for me. I also think there's no need for this commands to be available as an arg, but maybe other users think different.

In my case I use always the same format for all the reports, and if there's a case where I would use different formats I'd use the config files instead.

**Comment by kriskbx** [comment]
Like this:

```
# Time format for different parts of the report
# Instead of specifying one global time format you can specify one for every
# part of the report and the log command
timeFormat:
  log: "[%sign][%hours_overall]"
  stats: "[%sign][%days_overall]"
  issues: "[%sign][%hours_overall]"
  merge_requests: "[%sign][%hours_overall]"
  records: "[%sign][%days>d ][%hours>h ][%minutes>m ][%seconds>s]"
```
